server:
  port: 9000
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: system
          uri: lb://system
          predicates:
           - Path=/system/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
